Nombre = "Sebastian" 
#crear la variable nombre 
Apellido = "Beltran Guerrero"
# crear la variable apellido
Profesion = "Barberia"
#crear la variable profesion
edad = 24
#crear la variable edad
print ("Tu edad es:", edad )
#Declara una variable llamada edad y asígnale un número entero Luego imprímela
a = 14
b = 7
print ("La suma de a y b es:", a+b)
#Declara dos números enteros (a y b) y muestra su suma usando print.
print ("La resta de a y b es:", a-b)
#Declara dos números y muestra su resta.
print ("La multiplicacion de a y b es :", a*b,  )
#Muestra la multiplicación de dos números enteros.
print ("La division de a y b es:", a// b,)
#Muestra el resultado de dividir dos números enteros (usa división entera con //).
resto = 10%3
print ("El resto de dividir 10 entre tres es:", resto)
#Calcula el resto (módulo) de dividir 10 entre 3 e imprímelo.
a = 4
b = 5
c = 7
print ("Los numeros son:", a,b,c," \nLa suma  es:", a+b+c)
#Declara tres números y muestra su suma total.

ancho = 12
alto = 8
print ("El area del rectangulo es de medidas alto 8 y ancho 12:", ancho*alto)
#Declara una variable ancho y otra alto, luego imprime el área de un rectángulo (ancho * alto).
AñoN = 2000
AñoA = 2025
print ("Mi edad es:", AñoA-AñoN) 
#Declara tu año de nacimiento y el año actual, luego imprime tu edad.
numero = 6
doble = numero*2
triple = numero*3
cuadrado= numero **2
print ("El numero es:",numero, "\nEl doble es:",doble, "\nEl triple es:", triple, "\nEl cuadrado es:", cuadrado  )
#Declara un número entero y muestra el doble, el triple y el cuadrado de ese número.
