#=============FORMULARIO=============
print("FORMULARIO DE USUARIOS")
nombre = input("Ingrese su nombre numero uno")
nombre2 = input("ingrese su nombre numero dos")
apellido = input("ingrese su apellido")
apellido2 = input("ingrese su apellido dos")
#============DATOS NUMERICOS=========
edad=int(input("ingrese su edad"))
peso=float(input("ingrese su peso"))
telef=int(input("ingrese su telefono"))
altura=float(input("ingrese su altura"))
hijos=int(input("ingrese el numero de hijos"))
año_nacimiento=int(input("ingrese su año de nacimiento"))
mes_nacimiento=int(input("ingrese su mes de nacimineto"))
dia_nacimiento=int(input("ingrese su dia de nacimineto"))
cedula=int(input("ingrese su numero de cedula"))
#===============DATOS TEXTO O STRING==============
correo =input("ingrese su correo")
tipo_sangre =input("ingrese su tipo de sangre")
genero= input("ingrese su genero")
estado_civil =input("ingrese su estado civil")
eps =input("ingrese su EPS")
universidad =input("ingrese su universidad")
carrera =input("ingrese su carrera")
#==================================
("")
print ("el nombre completo es",nombre + " " + nombre2 + " " + apellido + " " +apellido2)
print("La edad es:",edad)
print("El peso es:",peso)
print("El telefono es:",telef)
print("La altura es:",altura)
print("La cantidad de hijos es:",hijos)
print("El año de nacimineto es:",año_nacimiento,mes_nacimiento,dia_nacimiento)
print("El numero de cedula es:",cedula)
print("El correro es:",correo)
print("El tipo de sangre es:", tipo_sangre)
print("El genero es:",genero)
print("El estado civil es:",estado_civil)
print("La EPS es:",eps)
print("La universidad es",universidad)
print("La carrera es:",carrera)

